In [ ]:
#Python Numpy

# Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

In [18]:
import numpy as np

print("NumPy Version:", np.__version__)


NumPy Version: 1.26.4


In [19]:
#Arrays in Numpy
# Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.

#Creating a Numpy Array 
import numpy as np
arr1 = np.array([1,2,3]) #Rank 1 Array
print(arr1)

arr2 = np.array([[1,2,3],
               [4,5,6]]) #Rank 2 Array
print(arr2)

#Creating an array from tuple
arr=np.array((1,3,2))
print(arr)

#Special Arrays
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
full = np.full((2, 2), 7)
eye = np.eye(3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Full:\n", full)
print("Identity Matrix:\n", eye)



[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[7 7]
 [7 7]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Ranges
# np.arange(start, stop, step) generates values from start to stop (exclusive) with a given step
arange = np.arange(0, 10, 2)  # Output: [0 2 4 6 8]

# np.linspace(start, stop, num) generates num evenly spaced values between start and stop (inclusive)
linspace = np.linspace(0, 1, 5)  # Output: [0.   0.25 0.5  0.75 1.  ]

print("Arange:", arange)
print("Linspace:", linspace)

Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [12]:
#Array Attributes
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Rank 2 Array
print(arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int32


In [16]:
#Array slicing and indexing 
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Accessing individual elements
print("Element at row 1, col 2:", arr[1, 2])  # 60

# Accessing full row or column
print("First row:", arr[0])       # [10 20 30]
print("First column:", arr[:, 0]) # [10 40 70]

# Slicing: extracting sub-arrays
print("Sub-array from (1,1) to end:\n", arr[1:, 1:])
# Output: [[50 60], [80 90]]

# More slicing examples
print("Middle column:", arr[:, 1])         # [20 50 80]
print("Last row reversed:", arr[2, ::-1])   # [90 80 70]
print("Diagonal:", arr.diagonal())          # [10 50 90]

Element at row 1, col 2: 60
First row: [10 20 30]
First column: [10 40 70]
Sub-array from (1,1) to end:
 [[50 60]
 [80 90]]
Middle column: [20 50 80]
Last row reversed: [90 80 70]
Diagonal: [10 50 90]


In [17]:
#Array Operations
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])

print("Add:", a + b)             # [5 7 9]
print("Multiply:", a * b)       # [4 10 18]
print("Exponent:", a ** 2)      # [1 4 9]
print("Square root:", np.sqrt(a)) # [1. 1.41 1.73]

# Broadcasting: apply operation to all rows
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix + 10:\n", matrix + 10)

Add: [5 7 9]
Multiply: [ 4 10 18]
Exponent: [1 4 9]
Square root: [1.         1.41421356 1.73205081]
Matrix + 10:
 [[11 12 13]
 [14 15 16]]


In [20]:
#Statistics 

stats=np.array([[1,2,3],[4,5,6]])
print("Mean:",np.mean(stats)) #Average of all elements
print("Median:",np.median(stats)) #Middle Value
print("Standard Deviation:",np.std(stats))
print("Max:",np.max(stats))
print("Min:",np.min(stats))


Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Max: 6
Min: 1


In [22]:
#Reshaping & Flattening

arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = arr.reshape((3, 2))   # Change shape to 3 rows, 2 cols
flattened = arr.flatten()       # Convert to 1D

print("Reshaped to 3x2:\n", reshaped)
print("Flattened:", flattened)

Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Flattened: [1 2 3 4 5 6]


In [23]:
# Stacking & Splitting
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Horizontal Stack:", np.hstack((a, b)))  # [1 2 3 4 5 6]
print("Vertical Stack:\n", np.vstack((a, b)))   # [[1 2 3], [4 5 6]]

Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [24]:
# Random Numbers
np.random.seed(42)
print("Random Array:", np.random.rand(2, 2))
print("Random Integers:", np.random.randint(0, 10, (2, 3)))

Random Array: [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
Random Integers: [[6 9 2]
 [6 7 4]]


In [25]:
#Missing/Special Values

arr = np.array([1, 2, np.nan, 4])
print("Is NaN:", np.isnan(arr))
print("Mean ignoring NaN:", np.nanmean(arr))
print("Replace NaN:", np.nan_to_num(arr))

Is NaN: [False False  True False]
Mean ignoring NaN: 2.3333333333333335
Replace NaN: [1. 2. 0. 4.]


In [26]:
# NumPy + Data Analysis

import pandas as pd

df = pd.DataFrame({
    'height': [150, 160, 170],
    'weight': [60, 65, 72]
})

arr = df.values
print("Numpy array from DataFrame:\n", arr)
print("BMI:", arr[:,1] / (arr[:,0]/100)**2)

Numpy array from DataFrame:
 [[150  60]
 [160  65]
 [170  72]]
BMI: [26.66666667 25.390625   24.91349481]


In [27]:
#  NumPy in ML (Linear Regression Example)

X = np.array([1, 2, 3, 4, 5])
y = np.array([3, 4, 2, 5, 6])

X_mean = np.mean(X)
y_mean = np.mean(y)

numerator = np.sum((X - X_mean) * (y - y_mean))
denominator = np.sum((X - X_mean) ** 2)
m = numerator / denominator
c = y_mean - m * X_mean

print("Linear Regression: y = {:.2f}x + {:.2f}".format(m, c))

Linear Regression: y = 0.70x + 1.90
